import "./css/globals.css";
import Footer from "./components/footer/footer";
import { Suspense } from "react";
import { usePathname } from "next/navigation";
import Navbar from "./components/navbar/navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  );
}
